# Generated by Django 2.2.6 on 2019-12-13 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the kit.', max_length=100, unique=True)),
                ('slug', models.CharField(blank=True, editable=False, help_text='Generated url path.', max_length=100)),
                ('description', models.TextField(help_text='Write the description of your kit!')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the kit was created.')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='The date and time this kit was updated.')),
                ('curator', models.ForeignKey(help_text='The name of the curator that maintains this kit.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
