# Generated by Django 3.0.1 on 2020-01-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(blank=True, help_text='Summary of your blog (optional)', max_length=100),
        ),
    ]
