# Generated by Django 3.0.1 on 2020-01-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200110_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
